# NumPy exercises

In [1]:
import pandas as pd
import numpy as np
# ^^^ pyforest auto-imports - don't write above this line
import numpy as np

In [26]:
a1 = np.array([1, 2,  3, 4, 5])
print(a1)
print("shape of a1: " + str(a1.shape))

a2 = np.array([
    [2, 6, 4], 
    [5, 8, 3]
])
print(a2)
print("shape of a2: " + str(a2.shape))

a3 = np.array([
    [1, 2], [3, 4],
    [4, 3]
])
print(a3)
print("shape of a3: " + str(a3.shape))

[1 2 3 4 5]
shape of a1: (5,)
[[2 6 4]
 [5 8 3]]
shape of a2: (2, 3)
[[1 2]
 [3 4]
 [4 3]]
shape of a3: (3, 2)


array([1, 2, 3, 4, 5])

array([[2, 6, 4],
       [5, 8, 3]])

In [16]:
d3_array = np.array([
    [1, 2], [3, 4],
    [4, 3], [1, 7]
])

In [17]:
d3_array

array([[1, 2],
       [3, 4],
       [4, 3],
       [1, 7]])

In [14]:
d1_array.dtype

dtype('int32')

In [21]:
for key, value in pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [4.2, 5.6, 9.9]])).items():
    print("key: " + str(key), "| of type: " + str(type(key)))
    print()
    print("value: ")
    print(str(value), "| of type: " + str(type(value)))
    print("-----------")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

key: 0 | of type: <class 'int'>

value: 
0    1.0
1    4.0
2    4.2
Name: 0, dtype: float64 | of type: <class 'pandas.core.series.Series'>
-----------
key: 1 | of type: <class 'int'>

value: 
0    2.0
1    5.0
2    5.6
Name: 1, dtype: float64 | of type: <class 'pandas.core.series.Series'>
-----------
key: 2 | of type: <class 'int'>

value: 
0    3.0
1    6.0
2    9.9
Name: 2, dtype: float64 | of type: <class 'pandas.core.series.Series'>
-----------


In [22]:
df1 = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [4.2, 5.6, 9.9]]))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [20]:
np.array([[1, 2, 3], [4, 5, 6], [4.2, 5.6, 9.9]])

<IPython.core.display.Javascript object>

array([[1. , 2. , 3. ],
       [4. , 5. , 6. ],
       [4.2, 5.6, 9.9]])

In [23]:
df1["Example Column"] = [8, 3, 4]

In [24]:
df1

0    1    2  Example Column
0  1.0  2.0  3.0               8
1  4.0  5.0  6.0               3
2  4.2  5.6  9.9               4

In [27]:
for key, value in df1.items():
    print("key: " + str(key), "| of type: " + str(type(key)))
    print()
    print("value: ")
    print(str(value), "| of type: " + str(type(value)))
    print("-----------")
    


key: 0 | of type: <class 'int'>

value: 
0    1.0
1    4.0
2    4.2
Name: 0, dtype: float64 | of type: <class 'pandas.core.series.Series'>
-----------
key: 1 | of type: <class 'int'>

value: 
0    2.0
1    5.0
2    5.6
Name: 1, dtype: float64 | of type: <class 'pandas.core.series.Series'>
-----------
key: 2 | of type: <class 'int'>

value: 
0    3.0
1    6.0
2    9.9
Name: 2, dtype: float64 | of type: <class 'pandas.core.series.Series'>
-----------
key: Example Column | of type: <class 'str'>

value: 
0    8
1    3
2    4
Name: Example Column, dtype: int64 | of type: <class 'pandas.core.series.Series'>
-----------


In [26]:
len(df1)

3

In [39]:
df1 = pd.DataFrame(np.ones(shape=(5, 8)))
df1

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

0    1    2    3    4    5    6    7
0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
3  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
4  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0

In [46]:
batch_size = 1
shuffle = False
batch_dict = {}
if shuffle:
    index_iterator = iter(np.random.permutation(len(df1)))  
else:
    index_iterator = range(len(df1))

    # Initialize batch, construct batch, append to batch_dict
batch = []
for index in index_iterator:  # iterate over indices using the iterator
    batch.append(df1[index])
# Initialize batch_dict, will be yielded
batch_dict = {}
for data_dict in batch:
    for key, value in data_dict.items():
        if key not in batch_dict:
            batch_dict[key] = [] # initializes column with key, if column doesn't exist
        batch_dict[key].append(value) # adds values to said column
if len(batch) == batch_size:
    batch_dict.append(batch)  # use yield keyword to define an iterable generator
    batch = []
batch_dict

{0: [1.0, 1.0, 1.0, 1.0, 1.0],
 1: [1.0, 1.0, 1.0, 1.0, 1.0],
 2: [1.0, 1.0, 1.0, 1.0, 1.0],
 3: [1.0, 1.0, 1.0, 1.0, 1.0],
 4: [1.0, 1.0, 1.0, 1.0, 1.0]}

In [42]:
for index in index_iterator:  # iterate over indices using the iterator
    print(df1[index])

0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
Name: 0, dtype: float64
0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
Name: 1, dtype: float64
0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
Name: 2, dtype: float64
0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
Name: 3, dtype: float64
0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
Name: 4, dtype: float64


In [87]:
class DataLoader:
    """
    Dataloader Class
    Defines an iterable batch-sampler over a given dataset
    """
    def __init__(self, dataset, batch_size=1, shuffle=False, drop_last=False, verbose=False):
        """
        :param dataset: dataset from which to load the data
        :param batch_size: how many samples per batch to load
        :param shuffle: set to True to have the data reshuffled at every epoch
        :param drop_last: set to True to drop the last incomplete batch,
            if the dataset size is not divisible by the batch size.
            If False and the size of dataset is not divisible by the batch
            size, then the last batch will be smaller.
        """
        self.dataset = dataset
        self.batch_size = batch_size
        self.shuffle = shuffle
        self.drop_last = drop_last
        self.verbose = verbose

    def __iter__(self):
        ########################################################################
        # TODO:                                                                #
        # Define an iterable function that samples batches from the dataset.   #
        # Each batch should be a dict containing numpy arrays of length        #
        # batch_size (except for the last batch if drop_last=True)             #
        # Hints:                                                               #
        #   - np.random.permutation(n) can be used to get a list of all        #
        #     numbers from 0 to n-1 in a random order                          #
        #   - To load data efficiently, you should try to load only those      #
        #     samples from the dataset that are needed for the current batch.  #
        #     An easy way to do this is to build a generator with the yield    #
        #     keyword, see https://wiki.python.org/moin/Generators             #
        #   - Have a look at the "DataLoader" notebook first. This function is #
        #     supposed to combine the functions:                               #
        #       - combine_batch_dicts                                          #
        #       - batch_to_numpy                                               #
        #       - build_batch_iterator                                         #
        #     in section 1 of the notebook.                                    #
        ########################################################################
        # depending on shuffle condition, iterate over indeces in dataset
        if self.shuffle:
            index_iterator = iter(np.random.permutation(len(self.dataset)))  
        else:
            index_iterator = iter(range(len(self.dataset)))
        # Initialize batch_dict, will be yielded
        batch_dict = {}
        
        # Initialize batch, construct batch, append to batch_dict
        batch = []
        for index in index_iterator:  # iterate over indices using the iterator
            batch.append(self.dataset[index])
            if self.verbose:
                print(index)
            for data_dict in batch:
                for key, value in data_dict.items():
                    if key not in batch_dict:
                        batch_dict[key] = [] # initializes column with key, if column doesn't exist
                    batch_dict[key].append(value) # adds values to said column

            # turn batch_dict into dict of numpy arrays
            numpy_batch = {}        
            for key, value in batch_dict.items():
                numpy_batch[key] = np.array(value)
                
            if len(batch) == self.batch_size:                    
                yield numpy_batch  # use yield keyword to define an iterable generator
            batch = []
            if len(batch) > 0 and not self.drop_last:
                yield numpy_batch
              

        ########################################################################
        #                           END OF YOUR CODE                           #
        ########################################################################

    def __len__(self):
        length = None
        ########################################################################
        # TODO:                                                                #
        # Return the length of the dataloader                                  #
        # Hint: this is the number of batches you can sample from the dataset. #
        # Don't forget to check for drop last!                                 #
        ########################################################################

        
        if self.drop_last:
            length = len(self.dataset) // self.batch_size # floor division
        else:
            if len(self.dataset) % self.batch_size > 0:
                length = int(len(self.dataset)/self.batch_size + 1)
            else:
                length = len(self.dataset)/self.batch_size
            

        ########################################################################
        #                           END OF YOUR CODE                           #
        ########################################################################
        return length

In [88]:
def pixel():
    return np.ndarray(shape=(3,))

def picture(heigth=2, width=3):
    pass

import random
raw_data = {}
for key in range(5):
    if key not in raw_data.keys():
        raw_data[key] = []
    raw_data[key].append(np.ndarray(shape=(5, 3)))
raw_data

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

{0: [array([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]])],
 1: [array([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]])],
 2: [array([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]])],
 3: [array([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]])],
 4: [array([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]])]}

In [97]:
raw_data = np.ndarray(shape=(5, 3, 5))

<IPython.core.display.Javascript object>

In [98]:
type(raw_data[1])

numpy.ndarray

In [89]:
pixel()

<IPython.core.display.Javascript object>

array([4.24399158e-314, 8.48798317e-314, 1.27319747e-313])

In [103]:
data = [raw_data, raw_data, raw_data]

In [104]:
dl = DataLoader(data, batch_size=2, shuffle=False, drop_last=True, verbose=True)

In [105]:
dl

In [106]:
for batch in dl:
    print(batch)

0


AttributeError: 'numpy.ndarray' object has no attribute 'items'

for index in index_iterator:  # iterate over indices using the iterator
            batch.append(self.dataset[index])

            for data_dict in batch:
                for key, value in data_dict.items():
                    if key not in batch_dict:
                        batch_dict[key] = [] # initializes column with key, if column doesn't exist
                    batch_dict[key].append(value) # adds values to said column

            # turn batch_dict into dict of numpy arrays
            numpy_batch = {}        
            for key, value in batch_dict.items():
                numpy_batch[key] = np.array(value)